#!/bin/sh
cd "${0%/*}" || exit
#------------------------------------------------------------------------------

wclean kOmegaSSTPDA_symbolic_regression
wclean kOmegaSSTPDA_incompressible
wclean kOmegaSSTPDA_compressible
wclean calcPDAFields

rm -f foamVersionThisIsCompiledFor

#------------------------------------------------------------------------------